Repository dotnet/designs, pull requests merged in 2020-07, with the labels that each got.

#139 Add spec for obsoletions in .NET 5
  accepted/2020/better-obsoletion/obsoletions-in-net5.md
Labels: api-approved, blocking

#138 Mark Windows-specific APIs
  accepted/2020/windows-specific-apis/windows-specific-apis.md
Labels: api-approved

#146 Update obsoletions spec to match implementation
  accepted/2020/better-obsoletion/obsoletions-in-net5.md
Labels: api-ready-for-review

#141 BinaryFormatter long-term obsoletion plan
  accepted/2020/better-obsoletion/binaryformatter-obsoletion.md
Labels: api-approved

#142 Add additional Windows-specific APIs
  accepted/2020/windows-specific-apis/windows-specific-apis.md
Labels: api-approved
